/*
 * Author: Dan Roberts, University of Phoenix Copyright 2012
 * Current Release Date: Monday March 12, 2012
 * Version: 1.1.0
 * Submitted for PRG421 Java Programming II | course at the University of Phoenix
 * Scope: 
 * Displays the amortization data in a table
 */
package MortgageCalculatorCR7;

import javax.swing.table.DefaultTableModel;


public class table extends javax.swing.JFrame implements Runnable {

    double principal;
    double interest;
    int years;

    /** Creates new form table */
    public table(double principal, double interest, int years) {
        initComponents();
        this.principal = principal;
        this.interest = interest;
        this.years = years;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Table_jPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_jTable = new javax.swing.JTable();
        loanPrincipal_jLabel = new javax.swing.JLabel();
        loanInterest_jLabel = new javax.swing.JLabel();
        term_jLabel = new javax.swing.JLabel();
        totalPaid_jLabel = new javax.swing.JLabel();
        principal_jLabel = new javax.swing.JLabel();
        interest_jLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Table_jPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Amortization Schedule", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 2, 11), new java.awt.Color(153, 0, 0))); // NOI18N

        table_jTable.setModel(amortizationModel);
        jScrollPane1.setViewportView(table_jTable);

        javax.swing.GroupLayout Table_jPanelLayout = new javax.swing.GroupLayout(Table_jPanel);
        Table_jPanel.setLayout(Table_jPanelLayout);
        Table_jPanelLayout.setHorizontalGroup(
            Table_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Table_jPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Table_jPanelLayout.setVerticalGroup(
            Table_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Table_jPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        loanPrincipal_jLabel.setText("1");

        loanInterest_jLabel.setText("2");

        term_jLabel.setText("3");

        totalPaid_jLabel.setText("4");

        principal_jLabel.setText("5");

        interest_jLabel.setText("6");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Table_jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(term_jLabel)
                    .addComponent(loanInterest_jLabel)
                    .addComponent(loanPrincipal_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalPaid_jLabel)
                    .addComponent(principal_jLabel)
                    .addComponent(interest_jLabel))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {interest_jLabel, loanInterest_jLabel, loanPrincipal_jLabel, principal_jLabel, term_jLabel, totalPaid_jLabel});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Table_jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loanPrincipal_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loanInterest_jLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(term_jLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalPaid_jLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(principal_jLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(interest_jLabel)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {interest_jLabel, loanInterest_jLabel, loanPrincipal_jLabel, principal_jLabel, term_jLabel, totalPaid_jLabel});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void run() {
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setVisible(true);

        createTable();
        putTotal();
    }

    public void putTotal() { // Creates the output data on the bottom of table panel
        loanPrincipal_jLabel.setText(myAmortization.loanPrincipal);
        loanInterest_jLabel.setText(myAmortization.loanInterest);
        term_jLabel.setText(myAmortization.term);
        totalPaid_jLabel.setText(myAmortization.totalPaid);
        principal_jLabel.setText(myAmortization.Principal);
        interest_jLabel.setText(myAmortization.Interest);
    }

    public void createTable() { // Creates the table panel
        myAmortization.principal = principal;
        myAmortization.interest = interest;
        myAmortization.years = years;

        myAmortization.createAmortization();
        amortizationModel.setDataVector(myAmortization.colData, myAmortization.colNames);

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Table_jPanel;
    private javax.swing.JLabel interest_jLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel loanInterest_jLabel;
    private javax.swing.JLabel loanPrincipal_jLabel;
    private javax.swing.JLabel principal_jLabel;
    private javax.swing.JTable table_jTable;
    private javax.swing.JLabel term_jLabel;
    private javax.swing.JLabel totalPaid_jLabel;
    // End of variables declaration//GEN-END:variables
    DefaultTableModel amortizationModel = new DefaultTableModel();
    AmortizationSchedule myAmortization = new AmortizationSchedule();
}
